onesite:
	@echo "*** Completed in onesite ***"

clean:
	TEMPCSVSTORE="../../../importers/onesite/tempCSVs"
	rm -f [a-z] rentroll.log log *.txt ${TEMPCSVSTORE}/*.csv rt.csv people.csv rentable.csv ra.csv custom.csv
	@echo "*** CLEAN completed in onesite ***"

test:
	./functest.sh
	@echo "*** TEST completed in onesite ***"

package:
	@echo "*** PACKAGE completed in onesite ***"
