all:
	@echo "*** Completed in jm1 ***"

clean:
	rm -f rentroll.log log llog ll.g err.txt [a-z] [a-z][1-9]
	@echo "*** CLEAN completed in jm1 ***"

test:
	./functest.sh
	@echo "*** TEST completed in jm1 ***"

package:
	cp *.csv ../../tmp/rentroll/example/csv/
	@echo "*** PACKAGE completed in jm1 ***"
