all:
	@echo "*** PACKAGE completed in newbiz ***"

clean:
	rm -f newbiz [a-z] [a-z][a-z0-9] llog *.g ./gold/*.g err.txt xxqq ver.go log rentroll.log fail
	@echo "*** CLEAN completed in newbiz ***"

test:
	touch fail
	./functest.sh
	@echo "*** TEST completed in newbiz ***"
	@rm -f fail
package:
	@echo "*** PACKAGE completed in newbiz ***"

secure:
	@rm -f config.json confdev.json confprod.json
