#!/bin/bash
MAJVER=1
MINVER=0
BLDNOFILE="./buildno"
BUILDNO=$(cat ${BLDNOFILE})
BUILDNO=$((BUILDNO + 1))
FNAME="ver.go"
VER=$(printf "%d.%d.%06d" ${MAJVER} ${MINVER} ${BUILDNO})
DAT=$(date)
cat >${FNAME} <<ZZ1EOF
package main
// THIS FILE IS AUTOGENERATED
// DO NOT EDIT
func getVersionNo() string { return "${VER}" }
func getBuildTime() string { return "${DAT}" }
ZZ1EOF
echo "${BUILDNO}" >${BLDNOFILE}