.TH rentroll 1 "January 15, 2016" "Version 0.1" "USER COMMANDS"
.SH NAME
rentroll \- Accord Office RentRoll Service
.SH SYNOPSIS
.B rentroll

.SH DESCRIPTION
.B Rentroll
provides the rentroll service in Accord Office. It consists of \fBrentroll(1)\fR, a 
web server,  and a web-based front end.

.SH GLOSSARY OF TERMS
.IP Payor
A person who is financially responsible for the rent of one or more property units.

.IP Property
A name referring to one or more buildings of \fBUnits\fR that are operated as a
distinct business enterprise. If there are multiple 
physical buildings, each having a separate address, the \fBProperty\fR address
will be the single physical building address that acts as the main business address for
the business enterprise.

.IP Tenant
A person who occupies a \fBUnit\fR within a \fBProperty\fR. A \fBTenant\fR may also 
be, but is not required to be, a \fBPayor\fR.

.IP Transactant
A person who is a \fBTenant\fR of a \fBProperty\fR, or the \fBPayor\fR of rent, or both.
Much of the information needed for a \fBPayor\fR is the same as the information needed
for a \fBTenant\fR. Rather than collecting this information in two places, the transactant
can be referenced by a \fBTenant\fR and/or a \fBPayor\fR so that information is
not duplicated.

.IP Unit
A building or portion of a building that has been separately demised for rental
to a \fBTenant\fB.

.SH OPTIONS

.P

.SH EXAMPLES

.P

.SH BUGS
No known bugs.

.SH AUTHOR
Steve Mansour (sman@accordinterests.com)
.SH "SEE ALSO"
.BR phonebook (1)
