.TH rentroll 1 "January 15, 2016" "Version 0.1" "USER COMMANDS"
.SH NAME
rentroll \- Accord Office RentRoll Service
.SH SYNOPSIS
.B rentroll
[\fB\-B\fR 
[\fB\-B\fR \fIdatabase_username\fR]
[\fB\-f\fR \fIfirstname\fR]
[\fB\-help\fR]
[\fB\-l\fR \fIlastname\fR]
[\fB\-N\fR \fIdatabase_name\fR]
[\fB\-p\fR \fIpasswd\fR]
[\fB\-R\fR]
[\fB\-r\fR \fIrole\fR]
[\fB\-u\fR \fIusername\fR]

.SH DESCRIPTION
.B Rentroll
provides the rentroll service in Accord Office. It consists of \fBrentroll(1)\fR, a 
web server,  and a web-based front end.


.SH OPTIONS

.P

.SH EXAMPLES

.P

.SH BUGS
No known bugs.

.SH AUTHOR
Steve Mansour (sman@accordinterests.com)
.SH "SEE ALSO"
.BR phonebook (1)
