all:
	@echo "*** Completed in ccc ***"

clean:
	rm -f rentroll.log log llog ll.g err.txt [a-z] [a-z][1-9]
	@echo "*** CLEAN completed in ccc ***"

test:
	./functest.sh
	@echo "*** TEST completed in ccc ***"

package:
	cp *.csv ../../tmp/rentroll/example/csv/
	cp *.html ../../tmp/rentroll/example/csv/
	@echo "*** PACKAGE completed in ccc ***"
