package rlib
// THIS FILE IS AUTOGENERATED
// DO NOT EDIT

// GetVersionNo returns the current version number
func GetVersionNo() string { return "1.2.000000" }
// GetBuildMachine returns the machine on which this executable was built
func GetBuildMachine() string { return "Steves-MacBook-Pro-2.local" }
// GetBuildTime returns the time this executable was built
func GetBuildTime() string { return "Sun Aug 12 11:24:19 PDT 2018" }
