upd: *.go
	go build
	@echo "*** Completed in upd ***"

clean:
	rm -f rentroll.log log llog ll.g err.txt [a-z] [a-z][a-z1-9] qq? upd
	@echo "*** CLEAN completed in upd ***"

test: upd
	./functest.sh
	@echo "*** TEST completed in upd ***"

package:
	@echo "*** PACKAGE completed in upd ***"
