newdb:
	#mysql --no-defaults < schema.sql
	@echo "*** completed in db/schema ***"

doit:
	mysql --no-defaults < schema.sql

clean:
	@echo "*** CLEAN completed in db/schema ***"

test:
	@echo "*** TEST completed in db/schema ***"

package:
	cp schema.sql ../../tmp/rentroll/
	@echo "*** PACKAGE completed in db/schema ***"
