all:
	@echo "*** Completed in gsr ***"

clean:
	rm -f rentroll.log log ll.g llog [a-z] [a-z][0-9]
	@echo "*** CLEAN completed in gsr ***"

test:
	./functest.sh
	@echo "*** TEST completed in gsr ***"

package:
	@echo "*** PACKAGE completed in gsr ***"
