engine:
	@echo "*** COMPLETED in rsp ***"

clean:
	rm -f *.txt [a-z] log rsplog rentroll.log
	@echo "*** CLEAN COMPLETE in rsp ***"

test:
	rm -f *.txt
	./func.sh
	@echo "*** TEST COMPLETE - ALL TESTS PASSED in rsp ***"

package:
	@echo "*** PACKAGE completed in rsp ***"
