package core

// constants for csv types
const (
	// RENTABLETYPECSV NO
	RENTABLETYPECSV = iota
	// PEOPLECSV NO
	PEOPLECSV = iota
	// RENTABLECSV NO
	RENTABLECSV = iota
	// RENTALAGREEMENTCSV NO
	RENTALAGREEMENTCSV = iota
	// CUSTOMATTRIUTESCSV NO
	CUSTOMATTRIUTESCSV = iota
)
