all:
	@echo "*** Completed in rex ***"

clean:
	rm -f rentroll.log log ll.g llog
	@echo "*** CLEAN completed in rex ***"

test:
	./functest.sh
	@echo "*** TEST completed in rex ***"

package:
	@echo "*** PACKAGE completed in rex ***"
