all:
	@echo "*** Completed in gsr1 ***"

clean:
	rm -f rentroll.log log ll.g llog [a-z] [a-z][0-9]
	@echo "*** CLEAN completed in gsr1 ***"

test:
	./functest.sh
	@echo "*** TEST completed in gsr1 ***"

package:
	@echo "*** PACKAGE completed in gsr1 ***"
