package ws
// THIS FILE IS AUTOGENERATED
// DO NOT EDIT

// GetVersionNo returns the current version number
func GetVersionNo() string { return "1.2.000000" }
// GetBuildMachine returns the machine on which this executable was built
func GetBuildMachine() string { return "sudip" }
// GetBuildTime returns the time this executable was built
func GetBuildTime() string { return "Thu Dec 28 13:41:45 IST 2017" }
