.TH rrbkup 1 "December 23, 2015" "Version 0.9" "USER COMMANDS"
.SH NAME
rrbkup \- back up the Accord RentRoll database
.SH SYNOPSIS
.B rrbkup
[\fB\-help\fR ]
[\fB\-N\fR \fIdatabase_name\fR]

.SH DESCRIPTION
.B rrbkup
make a backup of the Accord RentRoll database. Backups are
stored in a directory called 'bkup' which created in the current path
if necessary.  The file name will be rentroll\f\Idd\f\R.sql.gz and
\f\Idd\f\R will be the current day of the month.
For example, a backup made on
Jan 05 will be storedin bkup/rentroll05.sql.gz.  This backup will be
kept until Feb 05. When a backup is made on Feb 05, the new backup will overwrite
the file bkup/rentroll05.sql.gz. 
.SH OPTIONS
.TP
.IP "-B database_username"
Username for logging into the database server. Default name is "ec2-user"
.IP "-f"
Back up both the data in the database as well as the pictures of individuals.
If this option is not specified, only the data in the database is saved.
.IP "-help"
Lists the command options to stdout.
.IP "-N database_name"
The default name for the production database is "rentroll".
.SH EXAMPLES

.IP "rrbkup"
Performs a database backup.

.SH BUGS
No known bugs.

.SH AUTHOR
Steve Mansour (sman@accordinterests.com)
.SH "SEE ALSO"
.BR rrrestore (1),
