all:
	@echo "*** PACKAGE completed in bizdelete ***"

clean:
	rm -f bizdelete a00 [a-z] [a-z][a-z0-9] llog *.g ./gold/*.g err.txt xxqq ver.go log rentroll.log fail
	@echo "*** CLEAN completed in bizdelete ***"

test:
	touch fail
	./functest.sh
	@echo "*** TEST completed in bizdelete ***"
	@rm -f fail
package:
	@echo "*** PACKAGE completed in bizdelete ***"
