all:
	@echo "*** PACKAGE completed in newbiz ***"

clean:
	rm -f newbiz a00 [a-z] [a-z][a-z0-9] llog llog.g xxqq ver.go log rentroll.log fail
	@echo "*** CLEAN completed in newbiz ***"

test:
	touch fail
	./functest.sh
	@echo "*** TEST completed in newbiz ***"
	rm -f fail
package:
	@echo "*** PACKAGE completed in newbiz ***"
