all:
	@echo "*** Completed in rr1 ***"

clean:
	rm -f rentroll.log [a-z] [a-z][0-9a-z] log *.log *.g ./gold/*.g err.txt fail
	@echo "*** CLEAN completed in rr1 ***"

test:
	touch fail
	./functest.sh
	@echo "*** TEST completed in rr1 ***"
	@rm -f fail

package:
	@echo "*** PACKAGE completed in rr1 ***"
