all:
	@echo "*** Completed in rr1 ***"

clean:
	rm -f rentroll.log [a-z] [a-z][0-9a-z] log *.log
	@echo "*** CLEAN completed in rr1 ***"

test:
	./functest.sh
	@echo "*** TEST completed in rr1 ***"

package:
	@echo "*** PACKAGE completed in rr1 ***"
