all:
	@echo "*** Completed in rex ***"

clean:
	rm -f [a-z] rentroll.log log *.txt fail
	@echo "*** CLEAN completed in rex ***"

test:
	touch fail
	./functest.sh
	@echo "*** TEST completed in rex ***"
	@rm -f fail

package:
	@echo "*** PACKAGE completed in rex ***"
