all:
	@echo "*** Completed in rex ***"

clean:
	rm -f [a-z] rentroll.log log *.txt /tmp/onesite/*.csv rentabletypes_*.csv
	@echo "*** CLEAN completed in rex ***"

test:
	./functest.sh
	@echo "*** TEST completed in rex ***"

package:
	@echo "*** PACKAGE completed in rex ***"
