all:
	@echo "*** Completed in rrr ***"

clean:
	rm -f rentroll.log log llog ll.g
	@echo "*** CLEAN completed in rrr ***"

test:
	./functest.sh
	@echo "*** TEST completed in rrr ***"

package:
	@echo "*** PACKAGE completed in rrr ***"
