all:
	@echo "*** Completed in rrr ***"

clean:
	rm -f rentroll.log log llog ll.g err.txt [a-z] [a-z][a-z1-9] qq? fail
	@echo "*** CLEAN completed in rrr ***"

test:
	touch fail
	./functest.sh
	@echo "*** TEST completed in rrr ***"
	rm -f fail

package:
	@echo "*** PACKAGE completed in rrr ***"
